export const EDIT_FILTER_TEXT = 'EDIT_FILTER_TEXT';
export const SELECT_FOUNTAIN = 'SELECT_FOUNTAIN';
export const SELECT_FOUNTAIN_SUCCESS = 'SELECT_FOUNTAIN_SUCCESS';
export const DESELECT_FOUNTAIN = 'DESELECT_FOUNTAIN';

