export const EDIT_FILTER_TEXT = 'EDIT_FILTER_TEXT';
export const SELECT_FOUNTAIN = 'SELECT_FOUNTAIN';
export const HIGHLIGHT_FOUNTAIN = 'HIGHLIGHT_FOUNTAIN';
export const SELECT_FOUNTAIN_SUCCESS = 'SELECT_FOUNTAIN_SUCCESS';
export const DESELECT_FOUNTAIN = 'DESELECT_FOUNTAIN';
export const TOGGLE_LIST = 'TOGGLE_LIST';
export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const RETURN_TO_ROOT = 'RETURN_TO_ROOT';
export const NAVIGATE_TO_FOUNTAIN = 'NAVIGATE_TO_FOUNTAIN';
export const UPDATE_FILTER_CATEGORIES = 'UPDATE_FILTER_CATEGORIES';
export const CLOSE_NAVIGATION = 'CLOSE_NAVIGATION';

